
project_id = "aobjtwikccovikmfoicg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://supabase.com/dashboard/project/*/auth/users"]
jwt_expiry_limit = 3600

[functions.symptom-analyzer]
verify_jwt = false

[functions.emissao-nfe]
enabled = true
verify_jwt = true
import_map = "./functions/emissao-nfe/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/emissao-nfe/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/emissao-nfe/*.html" ]
